Repository nodeshift/ubi-nodejs-extension, pull requests merged in 2023-03, with the labels that each got.

#25 fix: address additional linter errors
  detect_test.go
  generate.go
  generate_test.go
Labels: semver:patch

#26 fix: fixup checks for Chdir
  detect_test.go
Labels: semver:patch

#27 fix: fix more lint failures
  generate_test.go
Labels: semver:patch

#28 feat: fixup after repo rename
  go.mod
Labels: semver:major

#29 fix: minor formatting fixup
  generate.go
Labels: semver:minor

#30 doc: initial version of README.md
  README.md
Labels: semver:minor

#32 fix: add missing step in instructions
  README.md
Labels: semver:patch

#33 fix: fixup extension.toml to work with jam pack
  extension.toml
Labels: semver:patch

#34 Packagesh script
  .gitignore
  README.md
  scripts/.util/tools.json
  scripts/.util/tools.sh
  scripts/build.sh
  scripts/package.sh
Labels: semver:patch
